name: Setup

description: Sets up PHP and Composer

inputs:
  php-version:
    description: The PHP version(s) you wish to use.
    required: true
  php-extensions:
    description: The PHP extensions you want to install.
    required: false
    default: dom, curl, libxml, mbstring, zip, pcntl, pdo, gd, redis, igbinary, msgpack, lzf, zstd, lz4, memcached, gmp, :php-psr

runs:
  using: composite
  steps:
    - name: Get PHP extension hash
      id: get-cache-hash
      env:
        PHP_EXTENSIONS: ${{ inputs.php-extensions }}
      run: echo $PHP_EXTENSIONS | md5sum | awk '{ print $1 }'
      shell: bash

    - name: Setup cache environment
      id: extcache
      uses: shivammathur/cache-extensions@v1
      with:
        php-version: ${{ inputs.php-version }}
        extensions: ${{ inputs.php-extensions }}
        key: ${{ steps.get-cache-hash.hash }}

    - name: Cache extensions
      uses: actions/cache@v4
      with:
        path: ${{ steps.extcache.outputs.dir }}
        key: ${{ steps.extcache.outputs.key }}
        restore-keys: ${{ steps.extcache.outputs.key }}

    - name: Setup PHP and Composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        extensions: ${{ inputs.php-extensions }}
        tools: composer:v2

    - name: Get Composer cache dir
      id: composer-cache-dir
      run: echo dir=$(composer config cache-files-dir) >> $GITHUB_OUTPUT
      shell: bash

    - name: Cache dependencies
      uses: actions/cache@v4.0.2
      with:
        key: composer-cache-${{ hashFiles('**/composer.lock') }}
        path: ${{ steps.composer-cache-dir.outputs.dir }}
        restore-keys: composer-cache-
